<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Amsel.ArenaConnect\Amsel.ArenaConnect.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Xdg.Directories" Version="0.2.0" />
    <PackageReference Include="SkiaSharp" Version="4.153.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" Version="4.153.1"
      Condition="$([MSBuild]::IsOsPlatform('Linux'))" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="4.153.1"
      Condition="$([MSBuild]::IsOsPlatform('Windows'))" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
